networks:
  shared-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - shared-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-network


  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/testDB
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network
    depends_on:
      - spring-app