version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    
  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/testDB 

  nginx-api:
    image: nginx:latest
    container_name: nginx-api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - spring-app

networks:
  app-network:
    driver: bridge